### ISSUE TITLE
curl timeout

### ISSUE THREAD

**Issue by codding-nepale** [TrixterTheTux/Pterodactyl-WHMCS#114]
Hello, when create server with the pterodactyl module it makes me his mistakes there:

`
curl error Connection timed out after 5002 milliseconds
get - https://panel.pinous-heberg.fr/api/application/nodes	
[]
Array
(
    [status_code] => 0
)
`

**Comment by iamkubi** [comment]
As you've been told for 3 days in a row now, this is a network issue and nothing related to the module.

**Comment by codding-nepale** [comment]
ok but how to fix this error ?

**Comment by trenutoo** [comment]
You have to troubleshoot your network connection between WHMCS and the Panel. The request takes too long to succeed and timeouts.

On rare occasions, it might be caused by bad network topology where the routing between the servers is bad, but that is, rare. The [curl timeout could be increased to 10 here.](https://github.com/pterodactyl/whmcs/blob/master/pterodactyl/pterodactyl.php#L62)

This is not a bug in the module.
