### ISSUE TITLE
Add possibility to assign minecraft version

### ISSUE THREAD

**Issue by soren33322** [TrixterTheTux/Pterodactyl-WHMCS#149]
Hi,
can you make, so we can select minecraft_version and build_version for MC in WHMCS.
Also JAVA, so the customer can select before they which version and java version they want.

JAVA version should be automatically selected when the version of minecraft is in that scope of the specified JAVA version.
REF: https://docs.mcserversoft.com/advanced/java-version

**Comment by danny6167** [comment]
As mentioned in your previous issue, setting variables such as Minecraft version is *already* an option and is documented in the WHMCS module FAQ. Please use the Discord for support questions.

The ability to automatically select the java version in the order form isn't something the module can do due to the way WHMCS is built. We can't manipulate the order form like that.
