### ISSUE TITLE
Password is incorrect

### ISSUE THREAD

**Issue by Sitmobedaf** [TrixterTheTux/Pterodactyl-WHMCS#23]
http://img11.lostpic.net/2018/10/03/805d0e8cd54b3bc18cdd6fdae91aba56.jpg
This password is incorrect. I send it to the client’s mail using {$ service_password}. Also, in the personal account, the password cannot be changed, the error "Failed to change the password."

**Comment by TrixterTheTux** [comment]
Hi,

The password and username fields are not used by the module because individual servers don't have a username or password. For the same reason changing password is also disabled.

Even if I had the username and password of the actual account, it would be useless as I don't have any way to track it eg. if the user changes their username/password. This also would be a security risk as passwords shouldn't be stored in plaintext.

Instead, you'd want to tell the client to check another email that is sent by Pterodactyl. It contains a link to set the account's password. Username is the same as the email.

**Comment by Sitmobedaf** [comment]
Pterodactyl itself should send this letter?

**Comment by TrixterTheTux** [comment]
Correct

**Comment by julianborghuis** [comment]
And is it possible to integrate that link for new products in the product details in whmcs?

**Comment by TrixterTheTux** [comment]
No.
