### ISSUE TITLE
Add $param "Username"

### ISSUE THREAD

**Issue by Stantastic** [TrixterTheTux/Pterodactyl-WHMCS#6]
Add the $param "Username" for customers to choose a username for Pterodactyl instead of a random generated one. Pre-Checking if username exists would be helpful tho.

**Comment by TrixterTheTux** [comment]
Now that I think of, I'm not going to handle this module side due to the number of complications this would bring. I'd need to verify if the username is used and then somehow tell the user that the username is in use, which I have no idea how to do with WHMCS as I only can fail the deployment in the function this is done not allowing me to prevent the user input. But pterodactyl already allows you to change your username in the "My Account" tab.
